version: "3.3"

services:
  jenkins:
    image: pauloromanenghi/jenkins-databases-dump
    container_name: jenkins-server
    privileged: true
    hostname: jenkinsserver
    user: root
    labels:
      com.example.description: "Jenkins-Server"
    ports: 
      - "8080:8080"
      - "50000:50000"
    networks:
      jenkins-net:
        aliases: 
          - jenkins-net
    restart: always
    volumes: 
     #- ./jenkins_scripts:/opt/jenkins_scripts
     - ./mysql_backup:/opt/mysql_backup
     - ./postgres_backup:/opt/postgres_backup
     - ./mssql_backup:/opt/mssql_backup
     - jenkins-data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
     
volumes: 
  jenkins-data:

networks:
  jenkins-net:
